
import { htmlToMarkdown, TFile, TFolder } from 'obsidian';
import { ZipEntryFile } from 'zip';
import { EpubBook } from './epub-import';
import { convertToMarkdown, hoistTableCaptions, injectCodeBlock, markElementAsLinkTarget, titleToBasename, toFrontmatterTagname } from '../ebook-transformers';

/**
 * Base class for assets in an e-pub ZIP archive that can be imported to Obsidian.
 */
export abstract class ImportableAsset {
    /**
     * asset source in the ZIP archive.
     * Needed for delazd loading of the asset contents
     */
    protected source: ZipEntryFile;

    /**
     * The relative folder path to an asset relative to the book.
     * Will also used as the relative folder path in the output folder.
     */
    assetFolderPath: string[];

    /**
     * The mimetype of the asset as defined in the book's manifest.
     */
    mimetype: string;

    /**
     * Create anew instance of an importable asset.
     *
     * @param source The ZIP file source of the asset.
     * @param href The book relative hyperlink of the asset
     * @param mimetype Asset mimetype
     */
    protected constructor(source: ZipEntryFile, href: string, mimetype: string) {
        this.mimetype = mimetype;
        this.source = source;
        const parts = href.split('/');
        this.assetFolderPath = parts.slice(0, parts.length - 1); // strip the filename
    }

    /**
     * A utility function to build a relative path to an asset.
     *
     * Works for botu source and output links as they share a common, relative folder path.
     *
     * @param basename the asset file's basename either in the book source or in the output folder.
     * @param extension THe asset file's extension
     * @param encode `true` to url encode the basename;
     * @returns a link relative to the book in the output or source folder.
     */
    protected makeAssetPath(basename: string, extension: string, encode: boolean): string {
        return [
            ...this.assetFolderPath,
            (encode ? encodeURIComponent(basename) : basename) + '.' + extension
        ].join('/');
    }

    /**
     * This property is computed by derived classes.
     *
     * @see makeAssetPath
     *
     * @param encode `true` to url-encode the path
     * @return Relative path of the asset relative to the book in the output folder.
     */
    abstract outputAssetPath(encode: boolean): string;

    get sourceAssetPath(): string {
        return this.makeAssetPath(this.source.basename, this.source.extension, false);
    }
    /**
     *
     * @param bookOutpuFolder Import the asset to the book's output folder.
     * @returns The imported file.
     */
    abstract import(bookOutpuFolder: TFolder): Promise<TFile>;

    /**
     * Get the fully qualified path to the output location of this asset.
     *
     * Missing folders in the output path are created if they do not exist-
     *
     * @param bookOutputFolder The out put folder
     * @returns full vault path.
     */
    protected async getVaultOutputPath(bookOutputFolder: TFolder): Promise<string> {
        const
            vault = bookOutputFolder.vault,
            fs = vault.adapter,
            folderCount = this.assetFolderPath.length;
        let folderPath = bookOutputFolder.path;
        for (let i = 0; i < folderCount; i++) {
            folderPath += '/' + this.assetFolderPath[i];
            if (!await fs.exists(folderPath)) {
                await vault.createFolder(folderPath);
            }
        }
        return bookOutputFolder.path + '/' + this.outputAssetPath(false);
    }
}

/**
 * Representation of a page in the epub book.
 */
export class PageAsset extends ImportableAsset {
    /**
     * The html document generated by {@link PageAsset.parse}.
     * @type {Document}
     */
    page?: Document;

    /**
     * The book's title as specified in the content map file `toc.ncx`
     * of the book.
     */
    pageTitle?: string;
    private book?: EpubBook;
    linkTargetMap = new Map<string, string>(); // id => sanitized ID

    constructor(source: ZipEntryFile, href: string, mimetype: string) {
        super(source, href, mimetype);
    }

    /**
     * Get a link to a page element or page in the book output folder,
     *
     * This method injects a code block into the location of the elment with the given
     * id for Markdown postprocessing to pick up.
     *
     * @param targetID Optional id to an element in the page identified by that id.
     * @returns link to a page element (if a `targetIS` was provided) or the
     *          page (if no `targetID` eas provided).
     */
    getOutputPageLink(encode: boolean, targetID?: string): string {
        const path = this.outputAssetPath(encode); // relative path to this node in the output folder
        if (!targetID || !this.page) {
            return path;
        }

        // check if we already have a merker for this id
        let id = this.linkTargetMap.get(targetID);
        if (!id) {
            // that targetID is not known - get the element with this id
            // and create a marker
            let e: Element | null;
            try {
                // try the canonical selector
                e = this.page.querySelector("#" + targetID);
            } catch (ex: any) {
                // fallback if targtID is malformed
                e = this.page.querySelector(`[id="${targetID}"]`);
            }

            if (!e) {
                return path; // no such element just link to the page
            }

            id = markElementAsLinkTarget(e);
            if (!id) {
                return path; // hust link to the page
            }
            this.linkTargetMap.set(targetID, id); // remember that
        }
        return path + "#^" + id; // the Obsidian link format;
    }

    outputAssetPath(encode: boolean): string {
        const basename = titleToBasename(this.pageTitle ?? this.source.basename);
        return this.makeAssetPath(basename, "md", encode);
    }

    async parse(book: EpubBook): Promise<void> {
        this.book = book;
        const html = (await this.source.readText())
            .replace(/&lt;/g, "＜")
            .replace(/&gt;/g, "＞"); // replace Obsidian unfriendly html entities.
        // we need to use the `text/html`so that Obsidian produces usable Markdown!
        this.page = book.parser.parseFromString(html, "text/html");
        if (this.page) {
            const body = this.page.body;
            // Apply document transformations to make the html Obsidian friendly
            injectCodeBlock(body);
            hoistTableCaptions(body);
        }
    }

    /**
     * Reconnect all links on this page pointing to other assets.
     *
     * Searches for all hyperlinks, extracts link target ids,
     * computes the correct link in the book output folder and
     * updated the each hyperlink.
     */
    reconnectLinks(book: EpubBook) {
        this.page?.body.querySelectorAll("a[href]").forEach(a => {
            const href = a.getAttribute("href");
            if (href) {
                const
                    parts = href.split("#"),
                    [path, id] = parts,
                    asset = path ? book.getAsset(path) : this;
                if (asset instanceof PageAsset) {
                    const link = asset.getOutputPageLink(true, id);
                    a.setAttribute("href", link);
                    // we also need to make sure the link text is compatible with
                    // markdown links
                    let txt = a.textContent;
                    if (txt) {
                        const sanitized = txt.replace(/([\]\[]+)/g, "\\$1");
                        if (sanitized.length !== txt.length) {
                            a.setText(sanitized);
                        }
                    }
                }
            }
        })
    }
    async import(bookOutpuFolder: TFolder): Promise<TFile> {
        if (!this.page) {
            throw new Error('Book page not available for import');
        }

        const
            outputPath = await this.getVaultOutputPath(bookOutpuFolder),
            toc = this.book?.toc,
            markdown = [
                "---",
                `book: "[[${toc?.outputAssetPath(false)}|${toc?.bookTitle}]]"`,
                `tags: ${toc?.tags}`,
                "---",
                "",
                convertToMarkdown(this.page)
            ];

        return bookOutpuFolder.vault.create(outputPath, markdown.join("\n"));
    }
}

/**
 * Media asset used on pages of the e-book.
 */
export class MediaAsset extends ImportableAsset {
    constructor(source: ZipEntryFile, href: string, mimetype: string) {
        super(source, href, mimetype);
    }

    outputAssetPath(encode: boolean): string {
        return this.makeAssetPath(this.source.basename, this.source.extension, encode);
    }

    /**
     * Import the asset into the corrent location of the book's output folder.
     *
     * @param bookOutputFolder The book's output folder.
     * @returns THe Obsidian file
     */
    async import(bookOutputFolder: TFolder): Promise<TFile> {
        const outputPath = await this.getVaultOutputPath(bookOutputFolder);
        return bookOutputFolder.vault.createBinary(outputPath, await this.source.read());
    }
}

/**
 * A link descriptor for one link in the content map defined in (toc.ncx)
 */
class NavLink {
    assetLink: string;
    level: number;
    linkText: string;

    constructor(level: number, navpoint: Element, book: EpubBook) {
        this.level = level;
        const
            text = navpoint.querySelector(':scope > navLabel > text'),
            content = navpoint.querySelector(':scope > content'),
            contentSrc = content?.getAttribute('src');

        this.linkText = text?.textContent ?? 'unknown';
        if (contentSrc) {
            const
                [srcPath, id] = contentSrc.split('#'),
                asset = book.getAsset(srcPath);
            if (asset instanceof PageAsset) {
                if (!asset.pageTitle) {
                    const navtext = text?.textContent;
                    if (navtext) {
                        asset.pageTitle = navtext;
                    }
                }
                this.assetLink = asset.getOutputPageLink(false, id);
            } else {
                this.assetLink = asset ? asset.outputAssetPath(false) : srcPath;
            }
        }
    }

    get markdownListItem(): string {
        const padding = ' '.repeat(this.level * 2);
        return `${padding}- [[${this.assetLink}|${this.linkText}]]`;
    }
}

/**
 * The book's content map.
 *
 * The content map is built from the books `toc.ncx` by parsing
 * the `<navMap>` element.
 *
 * WHen imported creates the book's title page containig:
 * - Frontmatter with book metadata
 * - Book content map.
 */
export class TocAsset extends ImportableAsset {
    bookTitle?: string;
    bookAuthor?: string;
    bookCoverImage?: string;
    bookDescription?: string;
    bookPublisher?: string;
    tags: string[] = [];
    // a flat version of the content map
    navList: NavLink[] = [];

    constructor(source: ZipEntryFile, href: string, mimetype: string) {
        super(source, href, mimetype);
    }

    async import(bookOutpuFolder: TFolder): Promise<TFile> {
        const
            path = await this.getVaultOutputPath(bookOutpuFolder),
            description = htmlToMarkdown(this.bookDescription as string ?? "-")
                .split("\n")
                .map(l => "> " + l);
        let content: string[] = [
            "---",
            `book: "${this.bookTitle}"`,
            `author: "${this.bookAuthor}"`,
            "aliases: ",
            `  - "${titleToBasename(this.bookTitle ?? bookOutpuFolder.name)}"`,
            `publisher: "${this.bookPublisher}"`,
            `tags: [${this.tags.join(",")}]`,
            "---",
            "",
            `> [!abstract] ${this.bookTitle}`,
            `> <span style="float:Right;">![[${this.bookCoverImage}|300]]</span>`,
            ...description,
            "",
            "# " + this.bookTitle,
        ];
        content.push("# Book Content Map");
        for (const navlink of this.navList) {
            content.push(navlink.markdownListItem);
        }
        return bookOutpuFolder.vault.create(path, content.join("\n"));
    }

    outputAssetPath(encode: boolean): string {
        return this.makeAssetPath('§ Title Page', 'md', encode);
    }

    private parseNavPoint(level: number, navPoint: Element, book: EpubBook): NavLink {
        const navlink = new NavLink(level, navPoint, book);
        this.navList.push(navlink);
        navPoint.querySelectorAll(':scope > navPoint')
            .forEach(pt => this.parseNavPoint(level + 1, pt, book));
        return navlink;
    }

    async parse(book: EpubBook): Promise<void> {
        const
            doc = book.parser.parseFromString(await this.source.readText(), 'application/xml'),
            docTitle = doc.querySelector('ncx > docTitle > text'),
            docAuthor = doc.querySelector('ncx > docAuthor > text'),
            navMap = doc.querySelector('ncx > navMap');

        this.bookTitle = docTitle?.textContent ?? book.title;
        this.bookAuthor = docAuthor?.textContent ?? book.author;
        this.bookPublisher = book.publisher;
        this.bookDescription = book.description;
        this.tags = book.tags;
        this.bookCoverImage = book.coverImage;;

        // now build the content map. Top level navigation links denote chapters
        const navPoints = navMap?.children;
        if (navPoints) {
            const navPointCount = navPoints.length;
            for (let i = 0; i < navPointCount; i++) {
                this.parseNavPoint(0, navPoints[i], book);
            }
        }
    }
}


